version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL
    image: epmgcip-connect-ed-ui:latest
    ports:
      - '3000:3000'
